apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-exporter
  labels:
    app: mikrotik-exporter
spec:
  selector:
    matchLabels:
      app: mikrotik-exporter
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mikrotik-exporter
      annotations: {}
    spec:
      containers:
        - name: mikrotik-exporter
          image: nshttpd/mikrotik-exporter:1.0.12-DEVEL
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: DEVICE
              valueFrom:
                configMapKeyRef:
                  name: mikrotik-exporter
                  key: device
            - name: ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: mikrotik-exporter
                  key: address
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mikrotik-exporter
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mikrotik-exporter
                  key: password
