---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter-service
  labels:
    app: mikrotik-exporter
spec:
  ports:
    - name: metrics
      port: 9436
      targetPort: 9436
      protocol: TCP
  selector:
    app: mikrotik-exporter
  type: ClusterIP
