apiVersion: v1
kind: PersistentVolume
metadata:
  name: karakeep-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/raiven/karakeep
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-pvc
spec:
  storageClassName: ""
  volumeName: karakeep-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: meili-pv
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   local:
#     path: /home/raiven/meili
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - cloud
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: meili-pvc
# spec:
#   storageClassName: ""
#   volumeName: meili-pv
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1Gi
