apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mermaid-live-editor.fullname" . }}
  labels:
    {{- include "mermaid-live-editor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mermaid-live-editor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mermaid-live-editor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        env:
          - name: PORT
            value: "{{ .Values.env.PORT }}"
      terminationGracePeriodSeconds: 30
