gitea:
  image: gitea/gitea:1.15.2-rootless
  environment:
    - GITEA__database__DB_TYPE=postgres
    - GITEA__database__HOST=db:5432
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=gitea
  restart: always
  volumes:
    - gitea-data:/var/lib/gitea
    - gitea-config:/etc/gitea  
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "3000:3000"
    - "2222:2222"
  links:
    - db

db:
  image: postgres:13
  restart: always
  environment:
    - POSTGRES_USER=gitea
    - POSTGRES_PASSWORD=gitea
    - POSTGRES_DB=gitea
  volumes:
    - gitea-postgres:/var/lib/postgresql/data