heimdall:
  image: ghcr.io/linuxserver/heimdall
  container_name: heimdall
  environment:
    - PGID=1000
    - PUID=1000
    - TZ=Asia/Taipei
  volumes:
    - heimdall-data:/config
  ports:
    - 11080:80
    - 11443:443
  restart: always