mc:
  container_name: mc
  image: itzg/minecraft-server
  ports:
    - 25565:25565
  environment:
    EULA: "TRUE"
    VERSION: "1.17.1"
    OPS: "ahoy"
  volumes:
    - mc-data:/data
  tty: true
  stdin_open: true
  restart: unless-stopped