version: 3

silent: true

vars:
  RUNTIME: nerdctl
  HOST_USER: "{{.USER}}"
  HOST_SSH_PUB:
    sh: cat ~/.ssh/id_ed25519.zed.pub 2>/dev/null || echo ""
  HOME_DIR:
    sh: echo $HOME
  TARGETARCH: arm64

tasks:
  build:
    desc: Builds the development container image
    preconditions:
      - sh: '[ -n "{{.HOST_SSH_PUB}}" ]'
        msg: "No SSH public key found. Please generate one with 'ssh-keygen -t ed25519'"
    cmds:
      - echo "Building Zed dev container with:"
      - echo "  HOST_USER {{.HOST_USER}}"
      - |
        {{.RUNTIME}} build \
          --platform linux/{{.TARGETARCH}} \
          --build-arg HOST_USER="{{.HOST_USER}}" \
          --build-arg HOST_SSH_PUB="{{.HOST_SSH_PUB}}" \
          --build-arg TARGETARCH={{.TARGETARCH}} \
          -t zed-dev .

  run:
    desc: Runs the development container with git config and SSH keys mounted
    deps: [build]
    cmds:
      - |
        docker run -d --name zed-remote \
        --restart unless-stopped \
        -w /home/$(whoami)/$(basename $(pwd)) \
        -p 2222:22 \
        -v ${HOME}/.gitconfig:/home/{{.HOST_USER}}/.gitconfig:ro \
        -v $(pwd):/home/$(whoami)/$(basename $(pwd)) \
        -v ${HOME}/.zsh_other_env:/home/coder/.zsh_other_env \
        -v ${HOME}/.ssh/known_hosts:/home/$(whoami)/.ssh/known_hosts:ro \
        -v /Users/raiven_kao/.colima/dev/docker.sock:/var/run/docker.sock \
        zed-dev
