apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-pv
spec:
  storageClassName: ""
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/raiven/lms
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-pvc
spec:
  storageClassName: ""
  volumeName: lms-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
