apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-pv
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/raiven/navidrome
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeName: navidrome-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi