image:
  repository: deluan/navidrome
  tag: latest

service:
  type: ClusterIP
  port: 4533
  nodePort: 32533

persistence:
  enabled: true
  existingClaim: navidrome-pvc

dataPath: /home/raiven/navidrome
logLevel: info

musicPath: /mnt/omv/drive/music

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  enabled: true
  class: "nginx"
  tls:
    hostname: music.omegaatt.com
    secretName: music-omegaatt-com-tls
  hostname: music.omegaatt.com
  path: /

env:
  - name: ND_BASEURL
    value: ""
  - name: ND_SCANSCHEDULE
    value: 1h
  - name: ND_SESSIONTIMEOUT
    value: 72h
  - name: ND_ENABLETRANSCODINGCONFIG
    value: "true"