apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-pv
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/raiven/photoprism
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeName: photoprism-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
