apiVersion: v1
kind: PersistentVolume
metadata:
  name: memos-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/raiven/memos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
spec:
  storageClassName: ""
  volumeName: memos-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
