FROM debian:bookworm

ARG NODE_VERSION=22

RUN apt update && apt install -y git curl

RUN <<EOF
curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x -o nodesource_setup.sh
bash nodesource_setup.sh
apt-get install -y nodejs
EOF

ENTRYPOINT ["npx"]
