image:
  repository: frooodle/s-pdf
  tag: latest

common:
  lang: zh_TW

service:
  type: ClusterIP
  targetPort: 8080
  port: 8080
  nodePort: 8080

persistence:
  enabled: false
  existingClaim: s-pdf-pvc

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
  enabled: true
  class: "nginx"
  tls:
    hostname: s-pdf.omegaatt.com
    secretName: omegaatt-tls
  hostname: s-pdf.omegaatt.com
  path: /
