apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-influxdb2-0-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: influx-influxdb2
    namespace: default
  local:
    path: /home/pv/influxdb2-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node