controllers:
  web:
    containers:
      web:
        image:
          repository: ghcr.io/hoarder-app/hoarder
          tag: 0.22.0
        env:
          HOARDER_VERSION: release
          MEILI_ADDR: http://hoarder-meilisearch:7700
          BROWSER_WEB_URL: http://hoarder-chrome:9222
          DATA_DIR: /data
          NEXTAUTH_URL: https://hoarder.omegaatt.com
          DISABLE_SIGNUPS: false
        envFrom:
          - secret: hoarder
  chrome:
    containers:
      chrome:
        image:
          repository: gcr.io/zenika-hub/alpine-chrome
          tag: 124
        command:
          - chromium-browser
          - --headless
          - --no-sandbox
          - --disable-gpu
          - --disable-dev-shm-usage
          - --remote-debugging-address=0.0.0.0
          - --remote-debugging-port=9222
          - --hide-scrollbars
          - --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb
  meilisearch:
    containers:
      meilisearch:
        image:
          repository: getmeili/meilisearch
          tag: v1.11.1
        env:
          MEILI_NO_ANALYTICS: true
service:
  web:
    controller: web
    ports:
      http:
        port: 3000
  chrome:
    controller: chrome
    ports:
      http:
        port: 9222
  meilisearch:
    controller: meilisearch
    ports:
      http:
        port: 7700
ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    hosts:
      - host: &host hoarder.omegaatt.com
        paths:
          - path: /
            service:
              identifier: web
              port: http
    tls:
      - hosts:
          - *host
        secretName: omegaatt-tls
persistence:
  web:
    existingClaim: hoarder-pvc
    advancedMounts:
      web:
        web:
          - path: /data
  meilisearch:
    existingClaim: meili-pvc
    advancedMounts:
      meilisearch:
        meilisearch:
          - path: /meili_data
