name: Build and Push Dev Containers

on:
  push:
    branches:
      - main
    paths:
      - "dev-container/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "main"

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if dev-container has changes
        id: check
        run: |
          git diff --name-only HEAD~1 HEAD | grep -q "^dev-container/" && echo "should_run=true" >> $GITHUB_OUTPUT || echo "should_run=false" >> $GITHUB_OUTPUT

  build-and-push:
    needs: [check-changes]
    if: github.event_name == 'workflow_dispatch' || needs.check-changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./dev-container
          file: ./dev-container/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: omegaatt36/dev-container:noble
          target: base
          build-args: |
            USERNAME=coder

      - name: Build and push python image
        uses: docker/build-push-action@v5
        with:
          context: ./dev-container
          file: ./dev-container/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: omegaatt36/dev-container:noble-python
          target: python
          build-args: |
            USERNAME=coder

      - name: Build and push node image
        uses: docker/build-push-action@v5
        with:
          context: ./dev-container
          file: ./dev-container/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: omegaatt36/dev-container:noble-node
          target: node
          build-args: |
            USERNAME=coder
            NODE_VERSION=23
